-- Repair deploys where migration history exists but the app tables are absent.

CREATE TABLE IF NOT EXISTS newsful_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email TEXT NOT NULL,
    password VARCHAR NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS newsful_saved_articles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    image TEXT,
    source TEXT,
    user_id INTEGER REFERENCES newsful_users(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE newsful_users
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER TABLE newsful_saved_articles
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ADD COLUMN IF NOT EXISTS source TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS newsful_users_email_uniq
    ON newsful_users (lower(email));

CREATE UNIQUE INDEX IF NOT EXISTS newsful_saved_articles_user_url_uniq
    ON newsful_saved_articles (user_id, url);

CREATE INDEX IF NOT EXISTS newsful_saved_articles_user_idx
    ON newsful_saved_articles (user_id);
