import express from 'express';
import morgan from 'morgan';
import cors from 'cors';
import helmet from 'helmet';
import config from './config.js';
import { createDb } from './db.js';
import { runMigrations } from './migrate.js';
import usersRouter from './users/users-router.js';
import authRouter from './auth/auth-router.js';
import articlesRouter from './saved-articles/articles-router.js';
import newsRouter from './news/news-router.js';

// App factory so tests can inject their own database connection.
export function makeApp(db) {
  const app = express();
  app.set('db', db);
  app.set('trust proxy', 1);

  if (config.NODE_ENV !== 'test') {
    app.use(morgan(config.isProduction ? 'tiny' : 'dev'));
  }
  app.use(helmet());
  app.use(cors());
  app.use(express.json());

  app.get('/', (req, res) => {
    res.json({ status: 'ok', name: 'newsful-api' });
  });

  app.use('/api/users', usersRouter);
  app.use('/api/auth', authRouter);
  app.use('/api/saved-articles', articlesRouter);
  app.use('/api/news', newsRouter);

  app.use((req, res) => {
    res.status(404).json({ error: 'Not found' });
  });

  // eslint-disable-next-line no-unused-vars
  app.use((error, req, res, next) => {
    console.error(error);
    const response = config.isProduction
      ? { error: 'Server error' }
      : { error: error.message };
    res.status(500).json(response);
  });

  return app;
}

let serverlessApp;
let ready;

async function ensureSchema(db) {
  await db.raw(`
    CREATE TABLE IF NOT EXISTS newsful_users (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      email TEXT NOT NULL,
      password VARCHAR NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS newsful_saved_articles (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      title TEXT NOT NULL,
      url TEXT NOT NULL,
      image TEXT,
      source TEXT,
      user_id INTEGER REFERENCES newsful_users(id) ON DELETE CASCADE NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    ALTER TABLE newsful_users
      ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

    ALTER TABLE newsful_saved_articles
      ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      ADD COLUMN IF NOT EXISTS source TEXT;

    CREATE UNIQUE INDEX IF NOT EXISTS newsful_users_email_uniq
      ON newsful_users (lower(email));

    CREATE UNIQUE INDEX IF NOT EXISTS newsful_saved_articles_user_url_uniq
      ON newsful_saved_articles (user_id, url);

    CREATE INDEX IF NOT EXISTS newsful_saved_articles_user_idx
      ON newsful_saved_articles (user_id);
  `);
}

export default async function handler(req, res) {
  const db = serverlessApp?.get('db') ?? createDb();
  serverlessApp ??= makeApp(db);

  ready ??= (async () => {
    await runMigrations();
    await ensureSchema(db);
  })().catch((error) => {
    ready = undefined; // let the next request retry
    throw error;
  });
  await ready;

  return serverlessApp(req, res);
}
